- name: Set up nginx with no tls
  hosts: webservers
  become: True
  vars:
    key_file: /etc/nginx/ssl/nginx.key
    cert_file: /etc/nginx/ssl/nginx.crt
    conf_file: /etc/nginx/sites-available/default
    server_name: localhost
  tasks:
    - name: apt install nginx
      apt: name=nginx update_cache=yes

    - name: mkdir /etc/nginx/ssl
      file: path=/etc/nginx/ssl state=directory

    - name: cp files/nginx.key
      copy: src=files/nginx.key dest={{ key_file }} owner=root mode=0600
      notify: restart nginx

    - name: cp files/nginx.crt
      copy: src=files/nginx.crt dest={{ cert_file }}
      notify: restart nginx

    - name: cp files/nginx.conf 
      template: src=templates/nginx.conf.j2 dest={{ conf_file }}
      notify: restart nginx

    - name: ln -s /etc/nginx/sites-available/default
      file: src={{ conf_file }} dest=/etc/nginx/sites-enabled/default state=link
      notify: restart nginx

    - name: template templates/index.html.j2 /usr/share/nginx/html/index.html 0644
      template: 
        src: templates/index.html.j2 
        dest: /usr/share/nginx/html/index.html
        mode: 0644

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted 
